# Material parameter profiles for spin decoherence simulation
# RECOMMENDED BALANCED SETTINGS for memory-efficient simulation

materials:
  
  Si_P:
    name: "Silicon-28 (³¹P-doped)"
    description: "Isotopically purified ²⁸Si:P, nuclear-spin-free, charge noise dominated"
    
    # Physics parameters
    gamma_e: 1.76e11  # rad/(s·T), electron gyromagnetic ratio
    T1: 10000.0e-6    # seconds, spin-flip time (very long)
    
    # Single OU noise model
    # FINAL PARAMETERS: Based on isotopically purified Si-28:P
    # References: Muhonen et al. (2014), Veldhorst et al. (2014)
    OU:
      B_rms: 4.0e-9    # Tesla, RMS magnetic field fluctuation (4.0 nT)
      tau_c_min: 3.0e-9    # seconds (3 ns)
      tau_c_max: 3.0e-3   # seconds (3 ms)
      tau_c_num: 50        # Dense sampling for better coverage
      notes: "Charge noise from surface/interface, isotopically purified >99.99% 28Si"
    
    # Double OU noise model (two timescales)
    Double_OU:
      # Fast component (residual hyperfine from 29Si, 4.7%)
      B_rms1: 2.27e-9    # Tesla (3.21 nT / √2, corrected)
      tau_c1: 0.05e-6   # seconds (fixed, ~50 ns)
      
      # Slow component (charge noise)
      B_rms2: 2.27e-9    # Tesla (3.21 nT / √2, corrected)
      tau_c2_min: 0.5e-6   # seconds
      tau_c2_max: 100.0e-6  # seconds (increased range)
      tau_c2_num: 20       # Reduced for faster execution (still sufficient for curve fitting)
      
      notes: "Fast: residual hyperfine, Slow: charge fluctuations"
    
    # Simulation parameters
    # FINAL PARAMETERS: Optimized for Si-28:P with B_rms = 4.0 nT
    # Expected T2 (QS regime) ≈ 200 μs, so T_max = 10 ms provides good coverage
    T_max: 10.0e-3   # seconds, max simulation time (10 ms, ≥50×T2_QS for good coverage)
    dt: 3.0e-11       # seconds, time step (30 ps, tau_c_min/100 for accuracy)
    M: 2000          # ensemble size (sufficient for bootstrap statistics)
    seed: 42
    
    # Literature references
    references:
      - "Kane, B. E. (1998). Nature 393, 133-137"
      - "Morello et al. (2010). Nature 467, 687-691"
      - "Tyryshkin et al. (2012). Nature Materials 11, 143-147"
    
    # Expected T2 range from experiments
    expected_T2_range: [1.0e-3, 10.0e-3]  # 1-10 ms
  
  GaAs:
    name: "GaAs Self-Assembled Quantum Dot"
    description: "Hyperfine interaction dominated (75As, 69Ga, 71Ga)"
    
    # Physics parameters
    gamma_e: 1.76e11  # rad/(s·T)
    T1: 100.0e-6      # seconds, ~100 μs
    
    # Single OU noise model
    OU:
      B_rms: 8.0e-6     # Tesla, Overhauser field fluctuation (correct for GaAs)
      # DISSERTATION FIX: Focus on MN regime for accurate slope measurement
      # ξ = γ_e * B_rms * tau_c = 1.76e11 * 8e-6 * tau_c = 1.408e6 * tau_c
      # For ξ < 1 (MN regime): tau_c < 0.71 μs
      # Focus on 0.05-0.5 μs range (ξ = 0.07-0.70) for pure MN regime
      tau_c_min: 0.05e-6    # seconds (50 ns, pure MN regime)
      tau_c_max: 0.5e-6     # seconds (500 ns, stay in MN regime)
      tau_c_num: 50        # Increased data points for better slope fit
      notes: "Nuclear spin flip-flop dynamics - MN regime focused for slope validation"
    
    # Double OU noise model
    Double_OU:
      # Fast component (nearby nuclei, strong coupling)
      B_rms1: 5.7e-6    # Tesla
      tau_c1: 0.05e-6   # seconds (50 ns, fixed)
      
      # Slow component (distant nuclei, weak coupling)
      B_rms2: 5.7e-6    # Tesla
      tau_c2_min: 0.5e-6    # seconds
      tau_c2_max: 10.0e-6   # seconds
      tau_c2_num: 25        # Sufficient data points
      
      notes: "Fast: near nuclei, Slow: far nuclei"
    
    # Simulation parameters
    T_max: 30.0e-6    # seconds (30 μs, sufficient for GaAs)
    dt: 0.1e-9         # seconds (0.1 ns, sufficient for accuracy and memory efficiency)
    M: 750            # ensemble size (balanced for memory)
    seed: 43
    
    # Literature references
    references:
      - "Loss & DiVincenzo (1998). Phys. Rev. B 57, 120"
      - "Petta et al. (2005). Science 309, 2180-2184"
      - "Bluhm et al. (2010). Nature Physics 7, 109-113"
    
    # Expected T2 range from experiments
    expected_T2_range: [1.0e-6, 10.0e-6]  # 1-10 μs
