# Material parameter profiles for spin decoherence simulation
# RECOMMENDED BALANCED SETTINGS for memory-efficient simulation

materials:
  
  Si_P:
    name: "Silicon-28 (³¹P-doped)"
    description: "Nearly nuclear-spin-free, charge noise limited"
    
    # Physics parameters
    gamma_e: 1.76e11  # rad/(s·T), electron gyromagnetic ratio
    T1: 10000.0e-6    # seconds, spin-flip time (very long)
    
    # Single OU noise model
    OU:
      B_rms: 3.21e-9   # Tesla, RMS magnetic field fluctuation (3.21 nT, corrected from 5 μT)
      tau_c_min: 0.1e-6    # seconds (avoid extreme MN regime)
      tau_c_max: 500.0e-6  # seconds (increased for better coverage)
      tau_c_num: 30        # Increased data points
      notes: "Charge noise from surface/interface"
    
    # Double OU noise model (two timescales)
    Double_OU:
      # Fast component (residual hyperfine from 29Si, 4.7%)
      B_rms1: 2.27e-9    # Tesla (3.21 nT / √2, corrected)
      tau_c1: 0.05e-6   # seconds (fixed, ~50 ns)
      
      # Slow component (charge noise)
      B_rms2: 2.27e-9    # Tesla (3.21 nT / √2, corrected)
      tau_c2_min: 0.5e-6   # seconds
      tau_c2_max: 100.0e-6  # seconds (increased range)
      tau_c2_num: 30       # Increased data points
      
      notes: "Fast: residual hyperfine, Slow: charge fluctuations"
    
    # Simulation parameters
    # CRITICAL: QS regime requires T_max >> T2_th for accurate fitting
    # For Si:P with T2* ≈ 2.5 ms (expected), need T_max >= 25 ms (10×T2*, sufficient)
    # MEMORY FIX: Reduced T_max from 50ms to 25ms and increased dt to 0.2ns
    # This gives N_steps = 125M (manageable) while maintaining accuracy
    # With tau_c_min = 0.1μs, dt = 0.2ns gives dt/tau_c = 0.002 (500 samples per tau_c, sufficient)
    T_max: 25.0e-3  # seconds, max simulation time (25 ms, 10×T2* for QS regime)
    dt: 0.2e-9       # seconds, time step (0.2 ns, balanced for accuracy and memory)
    M: 300          # ensemble size (reduced for memory efficiency, still sufficient for statistics)
    seed: 42
    
    # Literature references
    references:
      - "Kane, B. E. (1998). Nature 393, 133-137"
      - "Morello et al. (2010). Nature 467, 687-691"
      - "Tyryshkin et al. (2012). Nature Materials 11, 143-147"
    
    # Expected T2 range from experiments
    expected_T2_range: [1.0e-3, 10.0e-3]  # 1-10 ms
  
  GaAs:
    name: "GaAs Self-Assembled Quantum Dot"
    description: "Hyperfine interaction dominated (75As, 69Ga, 71Ga)"
    
    # Physics parameters
    gamma_e: 1.76e11  # rad/(s·T)
    T1: 100.0e-6      # seconds, ~100 μs
    
    # Single OU noise model
    OU:
      B_rms: 8.0e-6     # Tesla, Overhauser field fluctuation (correct for GaAs)
      tau_c_min: 0.1e-6    # seconds (avoid extreme MN regime)
      tau_c_max: 10.0e-6    # seconds (10 μs)
      tau_c_num: 30        # Increased data points
      notes: "Nuclear spin flip-flop dynamics"
    
    # Double OU noise model
    Double_OU:
      # Fast component (nearby nuclei, strong coupling)
      B_rms1: 5.7e-6    # Tesla
      tau_c1: 0.05e-6   # seconds (50 ns, fixed)
      
      # Slow component (distant nuclei, weak coupling)
      B_rms2: 5.7e-6    # Tesla
      tau_c2_min: 0.5e-6    # seconds
      tau_c2_max: 10.0e-6   # seconds
      tau_c2_num: 25        # Sufficient data points
      
      notes: "Fast: near nuclei, Slow: far nuclei"
    
    # Simulation parameters
    T_max: 30.0e-6    # seconds (30 μs, sufficient for GaAs)
    dt: 0.1e-9         # seconds (0.1 ns, sufficient for accuracy and memory efficiency)
    M: 750            # ensemble size (balanced for memory)
    seed: 43
    
    # Literature references
    references:
      - "Loss & DiVincenzo (1998). Phys. Rev. B 57, 120"
      - "Petta et al. (2005). Science 309, 2180-2184"
      - "Bluhm et al. (2010). Nature Physics 7, 109-113"
    
    # Expected T2 range from experiments
    expected_T2_range: [1.0e-6, 10.0e-6]  # 1-10 μs
